name: GymTrack
password: Password123
keyalias: mykey
database:
  driverClass: com.mysql.jdbc.Driver
  user: root
  password: Poppy2911
  url: jdbc:mysql://localhost:3306/GymTrack
  validationQuery: "/* MyService Health Check */ SELECT 1"