server:
   applicationConnectors:
       - type: https
         port: 8080
         keyStorePath: ssl.jks
         keyStorePassword: Poppy2911
         validateCerts: false
         validatePeers: false
       - type: http
         port: 8087
name: com.elliotb.GymTrack
password: Password123
keyalias: mykey
database:
  driverClass: com.mysql.jdbc.Driver
  user: root
  password: Poppy2911
  url: jdbc:mysql://localhost:3306/GymTrack
  validationQuery: "/* MyService Health Check */ SELECT 1"