server:
  applicationConnectors:
    - type: https
      port: 8087
      keyStorePath: ssl.jks
      keyStorePassword: Poppy2911
      enableCRLDP: true
    - type: http
      port: 8080
name: com.elliotb.GymTrack
password: Password123
keyalias: mykey
database:
  driverClass: com.mysql.jdbc.Driver
  user: root
  password: Poppy2911
  url: jdbc:mysql://localhost:3306/GymTrack
  validationQuery: "/* MyService Health Check */ SELECT 1"